### ISSUE TITLE
References in JOSS paper

### ISSUE THREAD

**Issue by landreman** [AlanPearl/diffopt#1]
For the [JOSS review](https://github.com/openjournals/joss-reviews/issues/7522):

Googling around quickly, it looks like another project to connect mpi with jax is https://github.com/mpi4jax/mpi4jax. How about citing their [paper](https://joss.theoj.org/papers/10.21105/joss.03419) and adding a few words in your manuscript about the similarities/differences?

Also some info is missing on the Scott reference.

**Comment by AlanPearl** [comment]
- The Scott reference is now fixed: [f9e0146](https://github.com/AlanPearl/diffopt/commit/f9e0146115e432104a50080ea178adef363e46c6)
- Thanks for bringing up mpi4jax, I will definitely cite it and add some clarification on why to use one or the other...

**Comment by AlanPearl** [comment]
I have pushed changes to the statement of need in a2b6e83 including references to similar past efforts, including the two mentioned in this thread. How does this look?

**Comment by landreman** [comment]
Looks good to me

**Comment by ewu63** [comment]
Good with me as well

**Comment by jbytecode** [comment]
Can we please close the resolved issues?

**Comment by AlanPearl** [comment]
Yes, this is now closed
