### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by landreman** [AlanPearl/diffopt#3]
For the [JOSS review](https://github.com/openjournals/joss-reviews/issues/7522)- The journal requires the following:

"Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?"

I didn't see discussion in the docs of how to run the tests. Consider adding a Github Actions workflow to run the tests automatically?

**Comment by AlanPearl** [comment]
Good catch. I just now pushed an automatic testing workflow (plus manual testing instructions) to the main branch
